CAMERA_INDEX = 0
FRAME_WIDTH = 640
FRAME_HEIGHT = 480

MODEL_PATH = "yolov8n.pt"
CONFIDENCE = 0.50

PERSON_ON_CONSECUTIVE_FRAMES = 3
PERSON_OFF_DELAY_SEC = 2.0

SERIAL_PORT = "/dev/serial0"
SERIAL_BAUD = 115200

SHOW_PREVIEW = True
