CAMERA_INDEX = 0
FRAME_WIDTH = 320
FRAME_HEIGHT = 240

MODEL_PATH = "yolov8n.pt"
CONFIDENCE = 0.50
YOLO_IMGSZ = 320  # YOLO推論時の入力サイズ。小さいほど軽くなるが検出精度は下がる

PROCESS_EVERY_N_FRAMES = 2  # Nフレームに1回だけYOLO推論する。大きいほど軽くなるが検出の反応が遅れる

PERSON_ON_CONSECUTIVE_FRAMES = 3
PERSON_OFF_DELAY_SEC = 2.0

SERIAL_PORT = "/dev/ttyAMA0"
SERIAL_BAUD = 115200

SHOW_PREVIEW = True
